PURGE RECYCLEBIN;

SET SERVEROUTPUT ON;

declare
    is_true number;
begin
    select count(*) 
    INTO IS_TRUE
    from dba_users where username='FOOD_DONATION_APP_ADMIN1';
    IF IS_TRUE > 0
    THEN
    EXECUTE IMMEDIATE 'DROP USER FOOD_DONATION_APP_ADMIN1 CASCADE';
    END IF;
END;
/

CREATE USER FOOD_DONATION_APP_ADMIN1 IDENTIFIED BY Password123# QUOTA 200M ON DATA;

GRANT CONNECT TO FOOD_DONATION_APP_ADMIN1 WITH ADMIN OPTION;

GRANT RESOURCE TO FOOD_DONATION_APP_ADMIN1 WITH ADMIN OPTION;

GRANT CREATE VIEW TO FOOD_DONATION_APP_ADMIN1 WITH ADMIN OPTION;

GRANT CREATE PROCEDURE TO FOOD_DONATION_APP_ADMIN1 WITH ADMIN OPTION;

GRANT CREATE USER TO FOOD_DONATION_APP_ADMIN1;

GRANT DROP USER TO FOOD_DONATION_APP_ADMIN1;

GRANT CREATE SEQUENCE TO FOOD_DONATION_APP_ADMIN1;

GRANT CREATE TABLE TO FOOD_DONATION_APP_ADMIN1;





