------------------------------------CREATE TABLE--------------------------------
------------####location_table_creation####-----------------------
SET SERVEROUTPUT ON;
create or replace procedure location_creation is table_name varchar2(1000);  
BEGIN
-- table creation query
   table_name:='
   CREATE TABLE LOCATION(
   ZIP_CODE VARCHAR2(10), 
   CITY_NAME VARCHAR2(30) NOT NULL, 
   STATE_NAME VARCHAR2(20) NOT NULL,
   CONSTRAINT ZP_PK PRIMARY KEY(ZIP_CODE)
   )';
   
   EXECUTE IMMEDIATE table_name;
end location_creation;
/
create or replace procedure location_drop is table_name varchar2(1000);  
BEGIN
-- table creation query
   table_name:='drop table LOCATION cascade constraints PURGE';
   
   EXECUTE IMMEDIATE table_name;
end location_drop;
/

DECLARE
        tbl_name varchar2(50);
        cnt NUMBER;
    BEGIN
        tbl_name := 'LOCATION';
        SELECT count(*) into cnt FROM user_tables where table_name = tbl_name;
        IF(cnt > 0)
        THEN
                DBMS_OUTPUT.PUT_LINE('**********TABLE LOCATION ALREADY EXISTS***************');
                -- call to table drop stored procedure 
                BEGIN 
                    location_drop;
                    DBMS_OUTPUT.PUT_LINE('**********TABLE LOCATION DROPPED***************');
                    location_creation;
                    DBMS_OUTPUT.PUT_LINE('**********TABLE LOCATION CREATED******************');
                END; 
                dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');
        ELSE
        -- call to table creation stored procedure 
            BEGIN 
             location_creation;
            END;    
        DBMS_OUTPUT.PUT_LINE('**************TABLE LOCATION CREATED******************');
        dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');
        END IF;
        EXCEPTION 
          when no_data_found then
           dbms_output.put_line('****************Table does not exist**************'); 
           -- call to table creation stored procedure 
           BEGIN 
             location_creation;
             dbms_output.put_line('*******************Table LOCATION created successfully******************');
             dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');
           END; 
            when others
                then
                dbms_output.put_line('********************Something went wrong********************');
                dbms_output.put_line(dbms_utility.format_error_stack);
dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');
END;
/


------------####Volunteer_table_creation####-----------------------
SET SERVEROUTPUT ON;
create or replace procedure volunteer_creation is table_name varchar2(2000);  
BEGIN
-- table creation query
   table_name:='
   CREATE TABLE VOLUNTEER(
   V_ID NUMBER GENERATED BY DEFAULT AS IDENTITY(START WITH 101 INCREMENT BY 1), 
   V_FIRST_NAME VARCHAR2(20) NOT NULL, 
   V_LAST_NAME VARCHAR2(20) NOT NULL, 
   V_USERNAME VARCHAR2(20) UNIQUE NOT NULL,
   V_PWD VARCHAR2(20) NOT NULL, 
   V_MOBILE_NO VARCHAR2(20) UNIQUE NOT NULL, 
   V_ADDRESS VARCHAR2(30) NOT NULL, 
   ZIP_CODE VARCHAR2(10) NOT NULL, 
   V_ACTIVE VARCHAR2(20) NOT NULL, 
   V_AVAILABILITY VARCHAR2(20) NOT NULL, 
   V_DATE_REGISTRATION DATE DEFAULT SYSDATE NOT NULL,
   CONSTRAINT VID_PK PRIMARY KEY(V_ID),
   CONSTRAINT ZIPCODE_FK FOREIGN KEY (ZIP_CODE) REFERENCES LOCATION(ZIP_CODE),
   CONSTRAINT check_v_mobileno CHECK (V_MOBILE_NO BETWEEN 1111111111 AND 9999999999) ENABLE,
   CHECK(REGEXP_LIKE(V_FIRST_NAME,''^[A-Za-z0-9]{1,16}$'')),
   CHECK(REGEXP_LIKE(V_LAST_NAME,''^[A-Za-z0-9]{1,16}$'')),
   CHECK(REGEXP_LIKE(V_USERNAME,''^[A-Za-z0-9]{1,16}$''))
   )';
   
   EXECUTE IMMEDIATE table_name;
end volunteer_creation;
/

create or replace procedure volunteer_drop is table_name varchar2(1000);  
BEGIN
-- table creation query
   table_name:='drop table VOLUNTEER cascade constraints PURGE';
   
   EXECUTE IMMEDIATE table_name;
end volunteer_drop;
/


DECLARE
        tbl_name varchar2(50);
        cnt NUMBER;
    BEGIN
        tbl_name := 'VOLUNTEER';
        SELECT count(*) into cnt FROM user_tables where table_name = tbl_name;
        IF(cnt > 0)
        THEN
                DBMS_OUTPUT.PUT_LINE('**********TABLE VOLUNTEER ALREADY EXISTS***************');
                -- call to table drop stored procedure 
                BEGIN 
                    volunteer_drop;
                    DBMS_OUTPUT.PUT_LINE('**********TABLE VOLUNTEER DROPPED***************');
                    volunteer_creation;
                    DBMS_OUTPUT.PUT_LINE('**********TABLE VOLUNTEER CREATED******************');
                END; 
                dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');                dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');
        ELSE
        -- call to table creation stored procedure 
            BEGIN 
             volunteer_creation;
            END;    
        DBMS_OUTPUT.PUT_LINE('**************TABLE VOLUNTEER CREATED******************');
        dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');
        END IF;
        EXCEPTION 
          when no_data_found then
           dbms_output.put_line('****************Table does not exist**************'); 
           -- call to table creation stored procedure 
           BEGIN 
             volunteer_creation;
             dbms_output.put_line('*******************Table VOLUNTEER created successfully******************');
             dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');
           END; 
            when others
                then
                dbms_output.put_line('********************Something went wrong********************');
                dbms_output.put_line(dbms_utility.format_error_stack);
dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');
END;
/

----------------------------------------------####Recipient_table_creation--------------------------------------------------
SET SERVEROUTPUT ON;
create or replace procedure recipient_creation is table_name varchar2(2000);  
BEGIN
-- table creation query
   table_name:='
   create table Recipient(
   R_ID NUMBER GENERATED BY DEFAULT AS IDENTITY(START WITH 101 INCREMENT BY 1),
   R_Username varchar2(20) UNIQUE NOT NULL, 
   National_ID number UNIQUE NOT NULL, 
   R_Pwd varchar2(20)NOT NULL, 
   R_First_Name varchar2(20) NOT NULL,
   R_Last_Name varchar2(20) NOT NULL,
   R_Mobile_No varchar2(20) UNIQUE NOT NULL, 
   R_Address varchar2(50) NOT NULL, 
   Zip_Code VARCHAR2(10) NOT NULL, 
   R_Income varchar2(20) NOT NULL,
   R_DATE_REGISTRATION DATE NOT NULL,
   R_Approval_status NUMBER DEFAULT 0,
   CONSTRAINT R_ID_PK1 PRIMARY KEY(R_ID),
   CONSTRAINT ZP_PK1 FOREIGN KEY(ZIP_CODE) REFERENCES LOCATION(ZIP_CODE),
   CONSTRAINT check_nationalID CHECK (National_ID BETWEEN 111111111 AND 999999999) ENABLE,
   CONSTRAINT check_R_Mobile_No CHECK (R_Mobile_No BETWEEN 1111111111 AND 9999999999) ENABLE
   )';
   
   EXECUTE IMMEDIATE table_name;
end recipient_creation;
/

create or replace procedure recipient_drop is table_name varchar2(1000);  
BEGIN
-- table creation query
   table_name:='drop table RECIPIENT cascade constraints PURGE';
   
   EXECUTE IMMEDIATE table_name;
end recipient_drop;
/


DECLARE
        tbl_name varchar2(50);
        cnt NUMBER;
    BEGIN
        tbl_name := 'RECIPIENT';
        SELECT count(*) into cnt FROM user_tables where table_name = tbl_name;
        IF(cnt > 0)
        THEN
                DBMS_OUTPUT.PUT_LINE('**********TABLE RECIPIENT ALREADY EXISTS***************');
                -- call to table drop stored procedure 
                BEGIN 
                    recipient_drop;
                    DBMS_OUTPUT.PUT_LINE('**********TABLE RECIPIENT DROPPED***************');
                    recipient_creation;
                    DBMS_OUTPUT.PUT_LINE('**********TABLE RECIPIENT CREATED******************');
                END; 
                dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');
        ELSE
        -- call to table creation stored procedure 
            BEGIN 
             recipient_creation;
            END;    
        DBMS_OUTPUT.PUT_LINE('**************TABLE RECIPIENT CREATED******************');
        dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');
        END IF;
        EXCEPTION 
          when no_data_found then
           dbms_output.put_line('****************Table does not exist**************'); 
           -- call to table creation stored procedure 
           BEGIN 
             recipient_creation;
             dbms_output.put_line('*******************Table RECIPIENT created successfully******************');
             dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');
           END; 
            when others
                then
                dbms_output.put_line('********************Something went wrong********************');
                dbms_output.put_line(dbms_utility.format_error_stack);
dbms_output.put_line('-----------------------------------------------------------------------------------------------------------');
END;
/